// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TP2.Data;

#nullable disable

namespace TP2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260215123009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TP2.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Films d'action et d'aventure",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Films comiques et humoristiques",
                            Name = "Comédie"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Films dramatiques et émotionnels",
                            Name = "Drame"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Films de science-fiction",
                            Name = "Science-Fiction"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Films d'horreur et thriller",
                            Name = "Horreur"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Films romantiques",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Films d'animation",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Documentaires",
                            Name = "Documentaire"
                        });
                });

            modelBuilder.Entity("TP2.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Deux hommes emprisonnés créent un lien fort au fil des années.",
                            Duration = 142,
                            GenreId = 3,
                            Rating = 9.3m,
                            ReleaseDate = new DateTime(1994, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Le patriarche vieillissant d'une dynastie criminelle transfère le contrôle à son fils réticent.",
                            Duration = 175,
                            GenreId = 3,
                            Rating = 9.2m,
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Batman affronte le Joker dans une bataille pour l'âme de Gotham City.",
                            Duration = 152,
                            GenreId = 1,
                            Rating = 9.0m,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Les vies de deux tueurs à gages, d'un boxeur et d'un gangster s'entremêlent.",
                            Duration = 154,
                            GenreId = 1,
                            Rating = 8.9m,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Pulp Fiction"
                        });
                });

            modelBuilder.Entity("TP2.Models.Movie", b =>
                {
                    b.HasOne("TP2.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("TP2.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
